/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get books by IDs
         * @description Get books by IDs
         */
        get: operations["get-books-by-idssearch-books"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/reactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add a reaction (LIKE, SUPPORT)
         * @description Add a reaction (LIKE, SUPPORT)
         */
        post: operations["add-reaction"];
        /**
         * Remove a reaction
         * @description Remove a reaction
         */
        delete: operations["remove-reaction"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/talks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get talks by book ID
         * @description Get talks by book ID
         */
        get: operations["get-talks-by-book"];
        put?: never;
        /**
         * Create a new talk
         * @description Create a new talk
         */
        post: operations["create-talk"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get anonymous user info
         * @description Get anonymous user info
         */
        get: operations["auth-me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/books/{bookId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get detailed information about a book
         * @description Get detailed information about a book
         */
        get: operations["get-book-detail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/customer/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send a message to customer service
         * @description Send a message to customer service
         */
        post: operations["create-customer-message"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/talks/recommend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get recommended talks
         * @description Get recommended talks
         */
        get: operations["get-recommend-talks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/talks/{talkId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update a talk
         * @description Update a talk
         */
        put: operations["update-talk"];
        post?: never;
        /**
         * Delete (hide) a talk
         * @description Delete (hide) a talk
         */
        delete: operations["delete-talk"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login/naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Naver Login (Not Registered)
         * @description Naver Login (Not Registered)
         */
        post: operations["auth-login-naver-"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/signup/naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Naver Signup
         * @description Naver Signup
         */
        post: operations["auth-signup-naver"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** TalkPageResponse */
        TalkPageResponse: {
            /** @description Page Number */
            number: number;
            /** @description Number of Elements */
            numberOfElements: number;
            /** @description Size */
            size: number;
            /** @description Is Last */
            last: boolean;
            /** @description Total Pages */
            totalPages: number;
            /** @description Pageable info */
            pageable: string;
            sort?: {
                /** @description Sort Unsorted */
                unsorted: boolean;
                /** @description Sort Sorted */
                sorted: boolean;
                /** @description Sort Empty */
                empty: boolean;
            };
            /** @description Is First */
            first: boolean;
            content?: {
                /** @description Like Count (snake_case alias) */
                like_count?: number | null;
                /** @description Support Count */
                supportCount: number;
                /** @description Like Count */
                likeCount: number;
                /** @description Content */
                content: string;
                /** @description Date to be hidden */
                dateToHidden: string;
                /** @description Book ID */
                bookId: string;
                /** @description Did I Like */
                didILike: boolean;
                /** @description Created At */
                createdAt: string;
                /** @description Is Modified */
                isModified: boolean;
                /** @description Did I Support */
                didISupport: boolean;
                /** @description Nickname */
                nickname: string;
                /** @description Support Count (snake_case alias) */
                support_count?: number | null;
                /** @description Talk ID */
                id: string;
                /** @description Is Modified (snake_case alias) */
                is_modified?: boolean | null;
                /** @description Member ID */
                memberId: string;
            }[];
            /** @description Is Empty */
            empty: boolean;
            /** @description Total Elements */
            totalElements: number;
        };
        /** ReactionRequest */
        ReactionRequest: {
            /** @description Reaction Type (LIKE, SUPPORT) */
            type: string;
            /** @description Talk ID */
            talkId: string;
        };
        /** TalkCreateRequest */
        TalkCreateRequest: {
            /** @description Hidden Date (Instant) */
            hidden?: string | null;
            /** @description Talk Content */
            content: string;
            /** @description Book ID */
            bookId: string;
        };
        /** TalkUpdateRequest */
        TalkUpdateRequest: {
            /** @description New content */
            content: string;
        };
        /** NaverLoginResponse */
        NaverLoginResponse: {
            /** @description Temporary nickname from provider */
            tempNickname?: string | null;
            /** @description Is registered user */
            isRegistered: boolean;
            /** @description Register token for signup */
            registerToken?: string | null;
        };
        /** TalkListResponse */
        TalkListResponse: {
            /** @description Like Count (alias) */
            like_count?: number | null;
            /** @description Support Count */
            supportCount: number;
            /** @description Like Count */
            likeCount: number;
            /** @description Content */
            content: string;
            /** @description Date to be hidden */
            dateToHidden: string;
            /** @description Book ID */
            bookId: string;
            /** @description Did I Like */
            didILike: boolean;
            /** @description Is Modified */
            isModified: boolean;
            /** @description Did I Support */
            didISupport: boolean;
            /** @description Nickname */
            nickname: string;
            /** @description Support Count (alias) */
            support_count?: number | null;
            /** @description Talk ID */
            id: string;
            /** @description Is Modified (alias) */
            is_modified?: boolean | null;
            /** @description Member ID */
            memberId: string;
        }[];
        /** IdResponse */
        IdResponse: {
            /** @description Created Talk ID */
            id: string;
        };
        /** AuthMeResponse */
        AuthMeResponse: {
            /** @description User Role */
            role: string;
            /** @description User Nickname */
            nickname: string;
            /** @description Login status */
            isLoggedIn: boolean;
            /** @description User ID */
            id?: (string | never) | null;
        };
        /** SignupRequest */
        SignupRequest: {
            /** @description Desired Nickname */
            nickname: string;
            /** @description Register Token from Login API */
            registerToken: string;
        };
        /** NaverLoginRequest */
        NaverLoginRequest: Record<string, never>;
        /** BookListResponse */
        BookListResponse: {
            /** @description Page number */
            number: number;
            "[]"?: {
                /** @description ISBN */
                isbn: string;
                /** @description Book ID */
                id: string;
                /** @description Book Title */
                title: string;
            };
            /** @description Is last page */
            last: boolean;
            /** @description Number of elements */
            numberOfElements: number;
            /** @description Page size */
            size: number;
            /** @description Pageable info */
            pageable: string;
            sort?: {
                /** @description Sort unsorted */
                unsorted: boolean;
                /** @description Sort sorted */
                sorted: boolean;
                /** @description Sort empty */
                empty: boolean;
            };
            /** @description Is first page */
            first: boolean;
            content?: {
                /** @description Thumbnail Image URL */
                thumbnailImageUrl: string;
                /** @description Author */
                author: string;
                /** @description ISBN */
                isbn: string;
                /** @description Book ID */
                id: string;
                /** @description Book Title */
                title: string;
            }[];
            /** @description Is empty */
            empty: boolean;
        };
        /** CustomerMessageRequest */
        CustomerMessageRequest: {
            /** @description Message content */
            content: string;
        };
        /** BookResponse */
        BookResponse: {
            /** @description Thumbnail Image URL */
            thumbnailImageUrl: string;
            /** @description Author */
            author: string;
            /** @description ISBN */
            isbn: string;
            /** @description Description */
            description: string;
            /** @description Book ID */
            id: string;
            /** @description External Link URL */
            externalLinkUrl: string;
            /** @description Book Title */
            title: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    "get-books-by-idssearch-books": {
        parameters: {
            query: {
                /** @description List of Book IDs */
                id: string;
                /** @description Search keyword */
                keyword: string;
                /** @description Page number (0-based) */
                page?: string;
                /** @description Page size */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookListResponse"];
                };
            };
        };
    };
    "add-reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ReactionRequest"];
            };
        };
        responses: {
            /** @description 202 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "remove-reaction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["ReactionRequest"];
            };
        };
        responses: {
            /** @description 202 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get-talks-by-book": {
        parameters: {
            query: {
                /** @description Book ID */
                bookId: string;
                /** @description Page number */
                page?: string;
                /** @description Page size */
                size?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TalkPageResponse"];
                };
            };
        };
    };
    "create-talk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["TalkCreateRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IdResponse"];
                };
            };
        };
    };
    "auth-me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthMeResponse"];
                };
            };
        };
    };
    "get-book-detail": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description The unique identifier of the book */
                bookId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookResponse"];
                };
            };
        };
    };
    "create-customer-message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["CustomerMessageRequest"];
            };
        };
        responses: {
            /** @description 202 */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "get-recommend-talks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TalkListResponse"];
                };
            };
        };
    };
    "update-talk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["TalkUpdateRequest"];
            };
        };
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "delete-talk": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Talk ID */
                talkId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 204 */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    "auth-login-naver-": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["NaverLoginRequest"];
            };
        };
        responses: {
            /** @description 200 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NaverLoginResponse"];
                };
            };
        };
    };
    "auth-signup-naver": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json;charset=UTF-8": components["schemas"]["SignupRequest"];
            };
        };
        responses: {
            /** @description 201 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
